### PR TITLE
Add a period.

### PR DESCRIPTION
**Pull request by adamoutler**
I'd like to trigger a new build so as to view the logs. The existing logs have expired.

### CODE REVIEW

**Comment by adamoutler** [comment]
Hello?

**Comment by faddat** [comment]
hey sir!

this has really gone a lot further than this can you tell me what you'd like to do?

**Comment by adamoutler** [comment]
I was trying to see this.  Looks like it failed. https://github.com/faddat/device-image-test/runs/6620506626?check_suite_focus=true

**Comment by adamoutler** [comment]
Can this be fixed?   This is used as an example on two sites.

**Pull request merged**
